{
    'name': 'Education Management System',
    'version': '0.1',
    'summary': 'Comprehensive management for educational institutions',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/student_views.xml',
        'views/course_views.xml',
        'views/timetable_views.xml',
        'views/attendance_views.xml',
        'views/exam_views.xml',
        'views/assignment_views.xml',
        'views/fees_views.xml',
        'views/library_views.xml',
        'views/transport_views.xml',
        'views/health_views.xml',
        'views/hostel_views.xml',
        'views/event_views.xml',
        'views/counseling_views.xml',
        'views/evaluation_views.xml',
        'views/inquiry_views.xml',
    ],
    'installable': True,
    'application': True,
}
